name: Nix on macOS (unstable)

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'outputs/home-conf.nix'
      - 'outputs/installation.nix'
      - 'build'
      - 'switch'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: "experimental-features = nix-command"

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: snuggle
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build nix-darwin config ❄️"
        run: ./setup/build.sh darwin-unstable
