name: NixOS

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'outputs/home-conf.nix'
      - 'outputs/installation.nix'
      - 'build'
      - 'switch'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.4.0

      - name: "Get pinned nixpkgs ❄️"
        id: pinned_nixpkgs
        run: echo "::set-output name=url::https://github.com/NixOS/nixpkgs/archive/refs/tags/21.11.tar.gz"

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v16

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: snuggle
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          
      - run: nix-shell --run "echo NixOK"

      - name: "Build NixOS config ❄️"
        run: ./build.sh ci-system
